name: chmod
description: Provides utility functions for running "chmod" command in Dart.
version: 0.1.0
author: hunnble <hunnnble@gmail.com>
homepage: https://github.com/hunnble/chmod

environment:
  sdk: ">=2.2.0 <3.0.0"